# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kngdR_CVsEkBlmr7e2WpfNFY7Cp5MR7Y
"""

#Exercise 1
# Author Abdallah
# State: ongoing

# Exercise 2
# Author : BM
# State: ongoing
!pip install pillow
import numpy as np 
from PIL import Image,ImageOps
import matplotlib.pyplot as plt
from wordcloud import WordCloud,STOPWORDS,ImageColorGenerator
from scipy.ndimage import gaussian_gradient_magnitude 
# Exercise 3
# Author: CA
# State: ongoing

# Exercise 4
# Author: BM
# State: ongoing

# Excercise 5
# Author : AH
# State: ongoing
